version: "3.8"

services:
  video-conferencing-frontend:
    container_name: video-conferencing-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - video-conferencing-backend
    environment:
      - API_URL=http://video-conferencing-backend:4000
      - PEER_URL=http://video-conferencing-backend
      - API_PORT=4000
    restart: always

  video-conferencing-backend:
    container_name: video-conferencing-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - API_PORT=4000
    restart: always
