version: "3.8"

services:
  video-conferencing-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - video-conferencing-backend
    environment:
      - API_URL=http://video-conferencing-backend:4000
      - PEER_URL=http://video-conferencing-backend
      - API_PORT=4000

  video-conferencing-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - API_PORT=4000
